#include "pch.h"
#include "SceneParticles.h"

#include <cstring>

// Offline-compiled (fxc) byte arrays, generated by the CMake build into
// shaders/CompiledShaders/ (on this target's private include path), same as Scene3D. The
// particle program is new; the debris pass reuses the scene3d mesh program bytecode (the
// arrays have internal linkage, so including the headers in this second TU is safe).
#include "sceneparticleVS.h" // g_sceneparticleVS
#include "sceneparticlePS.h" // g_sceneparticlePS
#include "scene3dVS.h"       // g_scene3dVS - reused for the debris triangles
#include "scene3dPS.h"       // g_scene3dPS

using winrt::com_ptr;
using winrt::check_hresult;
using namespace DirectX;

namespace Neuron::Graphics
{
  namespace
  {
    // Mirrors SceneCb in shaders/partials/scene3d.hlsli (row-major mvp + flat tint). Shared
    // by the debris pass's b0. alpha < 0 in color selects the per-vertex face colour.
    struct SceneConstants
    {
      float mvp[16];
      float color[4];
    };
    static_assert(sizeof(SceneConstants) == 80, "SceneConstants must match the SceneCb cbuffer");

    // Mirrors ShipLightCb in shaders/partials/scene3d.hlsli (b2). The debris pass binds it
    // with params.x = 0 (lighting off), so the scene3d VS passes the flat face colour through
    // and never touches the (identity) model-view here.
    struct ShipLightConstants
    {
      float mv[16];
      float lightDir[4];
      float ambient[4];
      float diffuse[4];
      float params[4]; // x = lit (0 / 1)
    };
    static_assert(sizeof(ShipLightConstants) == 128, "ShipLightConstants must match the ShipLightCb cbuffer");

    // Mirrors ParticleCb in shaders/partials/sceneparticle.hlsli (row-major view-projection).
    struct ParticleConstants
    {
      float mvp[16];
    };
    static_assert(sizeof(ParticleConstants) == 64, "ParticleConstants must match the ParticleCb cbuffer");

    // Build one camera-facing quad (two triangles) centred in front of the eye - the phase-1
    // bring-up smoke test. Uses the same world-space billboard basis (camera up / right) the
    // effects subsystem will use for real particles, and the same u_MVP = view-projection path,
    // so proving this quad proves the pass the simulation plugs into. The quad is symmetric in
    // +-right/+-up, so the sign of `right` only mirrors the sprite - it stays visible either way.
    void buildSmokeQuad(Neuron::Client::Camera& _cam, SceneParticles::ParticleVertex _out[6])
    {
      const XMFLOAT3 eyeF = _cam.Eye();
      const XMFLOAT3 atF = _cam.LookAt();
      const XMFLOAT3 upF = _cam.Up();
      const XMVECTOR eye = XMLoadFloat3(&eyeF);
      const XMVECTOR fwd = XMVector3Normalize(XMVectorSubtract(XMLoadFloat3(&atF), eye));
      const XMVECTOR right = XMVector3Normalize(XMVector3Cross(XMLoadFloat3(&upF), fwd));
      const XMVECTOR up = XMVector3Cross(fwd, right); // re-orthonormalised

      constexpr float DIST = 500.0f; // units in front of the eye
      constexpr float HALF = 120.0f; // half the quad size (ship-ish)
      const XMVECTOR centre = XMVectorMultiplyAdd(fwd, XMVectorReplicate(DIST), eye);
      const XMVECTOR rH = XMVectorScale(right, HALF);
      const XMVECTOR uH = XMVectorScale(up, HALF);

      const XMVECTOR bl = XMVectorSubtract(XMVectorSubtract(centre, rH), uH);
      const XMVECTOR br = XMVectorSubtract(XMVectorAdd(centre, rH), uH);
      const XMVECTOR tr = XMVectorAdd(XMVectorAdd(centre, rH), uH);
      const XMVECTOR tl = XMVectorAdd(XMVectorSubtract(centre, rH), uH);

      // Additive white at half alpha (0xAABBGGRR): visible over black, obviously additive.
      constexpr uint32_t COL = 0x80FFFFFFu;
      const auto put = [](SceneParticles::ParticleVertex& _v, FXMVECTOR _p, float _u, float _vv)
      {
        XMFLOAT3 f;
        XMStoreFloat3(&f, _p);
        _v = {f.x, f.y, f.z, _u, _vv, COL};
      };
      put(_out[0], bl, 0.0f, 1.0f);
      put(_out[1], br, 1.0f, 1.0f);
      put(_out[2], tr, 1.0f, 0.0f);
      put(_out[3], bl, 0.0f, 1.0f);
      put(_out[4], tr, 1.0f, 0.0f);
      put(_out[5], tl, 0.0f, 0.0f);
    }
  } // namespace

  void SceneParticles::Startup()
  {
    Shutdown(); // resources are created lazily (the device may not be up yet)
  }

  void SceneParticles::Shutdown()
  {
    s_partVs = nullptr;
    s_partPs = nullptr;
    s_partLayout = nullptr;
    s_partCb = nullptr;
    s_partVb = nullptr;
    s_partBlend = nullptr;
    s_partDepth = nullptr;
    s_sampler = nullptr;
    s_partSprite = nullptr;
    s_partCapacity = 0;
    s_particles.clear();
    s_meshVs = nullptr;
    s_meshPs = nullptr;
    s_meshLayout = nullptr;
    s_meshCb = nullptr;
    s_meshLightCb = nullptr;
    s_meshVb = nullptr;
    s_meshDepth = nullptr;
    s_raster = nullptr;
    s_meshCapacity = 0;
    s_debris.clear();
    s_ready = false;
    // s_smokeTest is a setting; keep it across device resets.
  }

  bool SceneParticles::EnsureResources()
  {
    if (s_ready)
      return true;

    ID3D11Device* device = Core::GetD3DDevice();
    if (!device)
      return false;

    // --- Additive particle program -----------------------------------------------------
    check_hresult(device->CreateVertexShader(g_sceneparticleVS, sizeof(g_sceneparticleVS), nullptr, s_partVs.put()));
    check_hresult(device->CreatePixelShader(g_sceneparticlePS, sizeof(g_sceneparticlePS), nullptr, s_partPs.put()));

    // Matches ParticleVertex { float x,y,z; float u,v; uint32 rgba; } (24 bytes).
    const D3D11_INPUT_ELEMENT_DESC partElems[] = {
      {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"COLOR", 0, DXGI_FORMAT_R8G8B8A8_UNORM, 0, 20, D3D11_INPUT_PER_VERTEX_DATA, 0},
    };
    check_hresult(device->CreateInputLayout(partElems, _countof(partElems), g_sceneparticleVS,
                                            sizeof(g_sceneparticleVS), s_partLayout.put()));

    D3D11_BUFFER_DESC pcbd{};
    pcbd.ByteWidth = sizeof(ParticleConstants);
    pcbd.Usage = D3D11_USAGE_DYNAMIC;
    pcbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    pcbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    check_hresult(device->CreateBuffer(&pcbd, nullptr, s_partCb.put()));

    // Additive: result = src.rgb * src.a + dst (per explosion.md - SrcBlend SRC_ALPHA,
    // DestBlend ONE). Overlapping particles accumulate into a glow; the soft sprite feathers
    // into the black. Alpha channel also additive so the target alpha stays sane under bloom.
    D3D11_BLEND_DESC abd{};
    abd.RenderTarget[0].BlendEnable = TRUE;
    abd.RenderTarget[0].SrcBlend = D3D11_BLEND_SRC_ALPHA;
    abd.RenderTarget[0].DestBlend = D3D11_BLEND_ONE;
    abd.RenderTarget[0].BlendOp = D3D11_BLEND_OP_ADD;
    abd.RenderTarget[0].SrcBlendAlpha = D3D11_BLEND_SRC_ALPHA;
    abd.RenderTarget[0].DestBlendAlpha = D3D11_BLEND_ONE;
    abd.RenderTarget[0].BlendOpAlpha = D3D11_BLEND_OP_ADD;
    abd.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
    check_hresult(device->CreateBlendState(&abd, s_partBlend.put()));

    // Depth test ON, write OFF: ships (which wrote depth) occlude particles, but particles do
    // not occlude each other or write depth - so the additive layer accumulates correctly.
    D3D11_DEPTH_STENCIL_DESC pdsd{};
    pdsd.DepthEnable = TRUE;
    pdsd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
    pdsd.DepthFunc = D3D11_COMPARISON_LESS_EQUAL;
    pdsd.StencilEnable = FALSE;
    check_hresult(device->CreateDepthStencilState(&pdsd, s_partDepth.put()));

    // Linear-clamp sampler for the soft sprite (smooth edges, no wrap bleed at the quad rim).
    D3D11_SAMPLER_DESC ssd{};
    ssd.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
    ssd.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;
    ssd.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
    ssd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
    ssd.ComparisonFunc = D3D11_COMPARISON_NEVER;
    ssd.MinLOD = 0.0f;
    ssd.MaxLOD = D3D11_FLOAT32_MAX;
    check_hresult(device->CreateSamplerState(&ssd, s_sampler.put()));

    // The soft particle sprite (cached by the TextureManager). If it fails to load, the pass
    // draws nothing (renderParticles guards on it) rather than punching black quads.
    s_partSprite = TextureManager::LoadTexture("Textures\\Particle.dds");

    // --- Debris program (reuses the scene3d mesh VS/PS) --------------------------------
    check_hresult(device->CreateVertexShader(g_scene3dVS, sizeof(g_scene3dVS), nullptr, s_meshVs.put()));
    check_hresult(device->CreatePixelShader(g_scene3dPS, sizeof(g_scene3dPS), nullptr, s_meshPs.put()));

    // Matches MeshVertex { float pos[3]; float nrm[3]; uint32 rgba; } (28 bytes).
    const D3D11_INPUT_ELEMENT_DESC meshElems[] = {
      {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"NORMAL", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"COLOR", 0, DXGI_FORMAT_R8G8B8A8_UNORM, 0, 24, D3D11_INPUT_PER_VERTEX_DATA, 0},
    };
    check_hresult(device->CreateInputLayout(meshElems, _countof(meshElems), g_scene3dVS,
                                            sizeof(g_scene3dVS), s_meshLayout.put()));

    D3D11_BUFFER_DESC mcbd{};
    mcbd.ByteWidth = sizeof(SceneConstants);
    mcbd.Usage = D3D11_USAGE_DYNAMIC;
    mcbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    mcbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    check_hresult(device->CreateBuffer(&mcbd, nullptr, s_meshCb.put()));
    mcbd.ByteWidth = sizeof(ShipLightConstants);
    check_hresult(device->CreateBuffer(&mcbd, nullptr, s_meshLightCb.put()));

    // Depth test + write, LESS_EQUAL: debris is solid geometry, occluding like the ships.
    D3D11_DEPTH_STENCIL_DESC mdsd{};
    mdsd.DepthEnable = TRUE;
    mdsd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ALL;
    mdsd.DepthFunc = D3D11_COMPARISON_LESS_EQUAL;
    mdsd.StencilEnable = FALSE;
    check_hresult(device->CreateDepthStencilState(&mdsd, s_meshDepth.put()));

    // Cull none (shared by both passes): debris tumbles freely and particle quads face the
    // camera, so neither depends on a winding order.
    D3D11_RASTERIZER_DESC rd{};
    rd.FillMode = D3D11_FILL_SOLID;
    rd.CullMode = D3D11_CULL_NONE;
    rd.DepthClipEnable = TRUE;
    rd.ScissorEnable = FALSE;
    check_hresult(device->CreateRasterizerState(&rd, s_raster.put()));

    s_ready = true;
    return true;
  }

  void SceneParticles::SetParticles(const ParticleVertex* _verts, int _count)
  {
    if (!_verts || _count <= 0)
      s_particles.clear();
    else
      s_particles.assign(_verts, _verts + _count);
  }

  void SceneParticles::SetDebris(const MeshVertex* _verts, int _count)
  {
    if (!_verts || _count <= 0)
      s_debris.clear();
    else
      s_debris.assign(_verts, _verts + _count);
  }

  void SceneParticles::renderDebris(const XMMATRIX& _viewProj)
  {
    if (s_debris.empty())
      return;

    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!ctx)
      return;

    // Grow the dynamic vertex buffer if this frame's debris is bigger than any before it.
    if (s_debris.size() > s_meshCapacity || !s_meshVb)
    {
      s_meshCapacity = s_debris.size() + s_debris.size() / 2 + 64;
      s_meshVb = nullptr;
      D3D11_BUFFER_DESC vbd{};
      vbd.ByteWidth = static_cast<UINT>(s_meshCapacity * sizeof(MeshVertex));
      vbd.Usage = D3D11_USAGE_DYNAMIC;
      vbd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
      vbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
      if (FAILED(Core::GetD3DDevice()->CreateBuffer(&vbd, nullptr, s_meshVb.put())))
        return;
    }

    D3D11_MAPPED_SUBRESOURCE mappedVb;
    if (FAILED(ctx->Map(s_meshVb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedVb)))
      return;
    std::memcpy(mappedVb.pData, s_debris.data(), s_debris.size() * sizeof(MeshVertex));
    ctx->Unmap(s_meshVb.get(), 0);

    // b0: mvp = view-projection (the verts are already in the render frame, so world is
    // identity). alpha < 0 tells the PS to use the per-vertex face colour. Uploaded transposed
    // (the shader consumes a column-vector matrix stored row-major: mul(u_MVP, pos)).
    SceneConstants cb{};
    XMFLOAT4X4 mvpT;
    XMStoreFloat4x4(&mvpT, XMMatrixTranspose(_viewProj));
    std::memcpy(cb.mvp, &mvpT, sizeof(cb.mvp));
    cb.color[0] = cb.color[1] = cb.color[2] = 0.0f;
    cb.color[3] = -1.0f;

    D3D11_MAPPED_SUBRESOURCE mappedCb;
    if (FAILED(ctx->Map(s_meshCb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedCb)))
      return;
    std::memcpy(mappedCb.pData, &cb, sizeof(cb));
    ctx->Unmap(s_meshCb.get(), 0);

    // b2: lighting off (params.x = 0). The scene3d VS then skips the light term and passes the
    // flat face colour through unchanged, so the (unused) model-view stays identity.
    ShipLightConstants lc{};
    lc.params[0] = 0.0f;

    D3D11_MAPPED_SUBRESOURCE mappedLc;
    if (FAILED(ctx->Map(s_meshLightCb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedLc)))
      return;
    std::memcpy(mappedLc.pData, &lc, sizeof(lc));
    ctx->Unmap(s_meshLightCb.get(), 0);

    ctx->OMSetDepthStencilState(s_meshDepth.get(), 0);
    ctx->RSSetState(s_raster.get());
    ctx->OMSetBlendState(nullptr, nullptr, 0xFFFFFFFF); // opaque (debris is solid)
    ctx->IASetInputLayout(s_meshLayout.get());
    ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    const UINT stride = sizeof(MeshVertex);
    const UINT offset = 0;
    ID3D11Buffer* vb = s_meshVb.get();
    ctx->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
    ctx->VSSetShader(s_meshVs.get(), nullptr, 0);
    ctx->PSSetShader(s_meshPs.get(), nullptr, 0);
    ID3D11Buffer* cb0 = s_meshCb.get();
    ID3D11Buffer* cb2 = s_meshLightCb.get();
    ctx->VSSetConstantBuffers(0, 1, &cb0);
    ctx->PSSetConstantBuffers(0, 1, &cb0);
    ctx->VSSetConstantBuffers(2, 1, &cb2);
    ctx->Draw(static_cast<UINT>(s_debris.size()), 0);
  }

  void SceneParticles::renderParticles(const XMMATRIX& _viewProj, Neuron::Client::Camera& _camera)
  {
    // This frame's source verts: the live batch, or (phase-1 bring-up) a single camera-facing
    // smoke quad so the pass is provable before the simulation feeds it.
    ParticleVertex smoke[6];
    const ParticleVertex* verts = s_particles.data();
    size_t count = s_particles.size();
    if (count == 0)
    {
      if (!s_smokeTest)
        return;
      buildSmokeQuad(_camera, smoke);
      verts = smoke;
      count = 6;
    }

    // The additive PS samples the sprite; without it the pass draws nothing (black * colour),
    // so skip rather than upload/draw for no pixels.
    ID3D11ShaderResourceView* spriteSrv =
      (s_partSprite && s_partSprite->IsLoaded()) ? s_partSprite->GetShaderResourceView() : nullptr;
    if (!spriteSrv)
      return;

    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!ctx)
      return;

    if (count > s_partCapacity || !s_partVb)
    {
      s_partCapacity = count + count / 2 + 64;
      s_partVb = nullptr;
      D3D11_BUFFER_DESC vbd{};
      vbd.ByteWidth = static_cast<UINT>(s_partCapacity * sizeof(ParticleVertex));
      vbd.Usage = D3D11_USAGE_DYNAMIC;
      vbd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
      vbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
      if (FAILED(Core::GetD3DDevice()->CreateBuffer(&vbd, nullptr, s_partVb.put())))
        return;
    }

    D3D11_MAPPED_SUBRESOURCE mappedVb;
    if (FAILED(ctx->Map(s_partVb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedVb)))
      return;
    std::memcpy(mappedVb.pData, verts, count * sizeof(ParticleVertex));
    ctx->Unmap(s_partVb.get(), 0);

    // b0: u_MVP = view-projection, uploaded transposed (column-vector matrix stored row-major).
    ParticleConstants cb{};
    XMFLOAT4X4 mvpT;
    XMStoreFloat4x4(&mvpT, XMMatrixTranspose(_viewProj));
    std::memcpy(cb.mvp, &mvpT, sizeof(cb.mvp));

    D3D11_MAPPED_SUBRESOURCE mappedCb;
    if (FAILED(ctx->Map(s_partCb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedCb)))
      return;
    std::memcpy(mappedCb.pData, &cb, sizeof(cb));
    ctx->Unmap(s_partCb.get(), 0);

    ctx->OMSetDepthStencilState(s_partDepth.get(), 0); // test on, write off
    ctx->RSSetState(s_raster.get());
    const float blendFactor[4] = {0, 0, 0, 0};
    ctx->OMSetBlendState(s_partBlend.get(), blendFactor, 0xFFFFFFFF); // additive
    ctx->IASetInputLayout(s_partLayout.get());
    ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    const UINT stride = sizeof(ParticleVertex);
    const UINT offset = 0;
    ID3D11Buffer* vb = s_partVb.get();
    ctx->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
    ctx->VSSetShader(s_partVs.get(), nullptr, 0);
    ctx->PSSetShader(s_partPs.get(), nullptr, 0);
    ID3D11Buffer* cb0 = s_partCb.get();
    ctx->VSSetConstantBuffers(0, 1, &cb0);
    ID3D11SamplerState* samp = s_sampler.get();
    ctx->PSSetSamplers(0, 1, &samp);
    ctx->PSSetShaderResources(0, 1, &spriteSrv);
    ctx->Draw(static_cast<UINT>(count), 0);

    // Unbind the sprite SRV so it can't linger on the PS input if a later pass binds that slot
    // as an output (defensive; the composite pass reads its own targets).
    ID3D11ShaderResourceView* nullSrv = nullptr;
    ctx->PSSetShaderResources(0, 1, &nullSrv);
  }

  void SceneParticles::Render(ID3D11RenderTargetView* _rtv, ID3D11DepthStencilView* _dsv,
                              Neuron::Client::Camera& _camera, int _vpX, int _vpY, int _vpW, int _vpH)
  {
    if (!_rtv || !_dsv || _vpW <= 0 || _vpH <= 0)
      return;
    if (!EnsureResources())
      return;

    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!ctx)
      return;

    // Draw over the ship pass's colour + depth (no clear); the target and depth buffer are the
    // ones RenderModels just used, so the effects register with the world.
    ID3D11RenderTargetView* rtvs[1] = {_rtv};
    ctx->OMSetRenderTargets(1, rtvs, _dsv);

    D3D11_VIEWPORT vp{};
    vp.TopLeftX = static_cast<float>(_vpX);
    vp.TopLeftY = static_cast<float>(_vpY);
    vp.Width = static_cast<float>(_vpW);
    vp.Height = static_cast<float>(_vpH);
    vp.MinDepth = 0.0f;
    vp.MaxDepth = 1.0f;
    ctx->RSSetViewports(1, &vp);

    // Row-vector DirectXMath matrices (p' = p * M); the shaders consume column-vector matrices
    // stored row-major, so the uploads inside each pass transpose. Same convention as Scene3D.
    const XMMATRIX viewProj = XMMatrixMultiply(_camera.View(), _camera.Projection());

    // Debris first (opaque, depth-writing), then the additive particles over it (depth-tested,
    // no write) so the glow accumulates against the solid fragments.
    renderDebris(viewProj);
    renderParticles(viewProj, _camera);
  }
}
