#include "pch.h"
#include "Scene3D.h"

#include <cstring>
#include <utility>

#include "SceneProjection.h"

#include "Renderer.h" // platform_renderer() -> master palette (planet/sun billboard colours)

// Offline-compiled (fxc) byte arrays, generated by the CMake build into
// shaders/CompiledShaders/ (on this target's private include path), same as Render2D.
#include "scene3dPS.h" // g_scene3dPS
#include "scene3dVS.h" // g_scene3dVS
#include "scenebbPS.h" // g_scenebbPS - planet/sun billboard pixel shader
#include "scenebbVS.h" // g_scenebbVS - planet/sun billboard vertex shader
#include "skyboxPS.h"  // g_skyboxPS  - procedural skybox background
#include "skyboxVS.h"  // g_skyboxVS  - full-screen-triangle skybox vertex shader
#include "dustPS.h"    // g_dustPS    - dust points (starfield in the scene pass)
#include "dustVS.h"    // g_dustVS

using winrt::com_ptr;
using winrt::check_hresult;

namespace Neuron::Graphics
{
  namespace
  {
    // Depth range for the flight scene. Near just in front of the eye (the legacy path
    // clamped z <= 0 to 1); far past the ship cull distance (space.cpp removes ships at
    // distance > 57344). D32_FLOAT keeps ample precision across this range.
    constexpr float kNearZ = 1.0f;
    constexpr float kFarZ = 131072.0f;

    // Legacy planet/sun object types (drawn as billboards, not ship meshes).
    constexpr int kShipPlanet = -1;
    constexpr int kShipSun = -2;

    // Mirrors SceneCb in shaders/partials/scene3d.hlsli (row-major mvp + flat tint).
    struct SceneConstants
    {
      float mvp[16];
      float color[4];
    };
    static_assert(sizeof(SceneConstants) == 80, "SceneConstants must match the SceneCb cbuffer");

    // Mirrors BillboardCb in shaders/partials/scenebb.hlsli (secondary colour + params).
    struct BillboardParams
    {
      float colorB[4];
      float params[4]; // x = mode (0 sun, 1 ring, 2 disk, 3 banded)
    };
    static_assert(sizeof(BillboardParams) == 32, "BillboardParams must match the BillboardCb cbuffer");

    // Mirrors ShipLightCb in shaders/partials/scene3d.hlsli (model-view + directional
    // light). Ship-only (b2); billboards do not use it.
    struct ShipLightConstants
    {
      float mv[16];
      float lightDir[4];
      float ambient[4];
      float diffuse[4];
      float params[4]; // x = lit (0 / 1)
    };
    static_assert(sizeof(ShipLightConstants) == 128, "ShipLightConstants must match the ShipLightCb cbuffer");

    // Mirrors SkyboxCb in shaders/partials/skybox.hlsli (gradient colours + star params).
    struct SkyboxParams
    {
      float top[4];    // gradient colour at the top of the view
      float bottom[4]; // gradient colour at the bottom
      float params[4]; // x = star threshold, y = star brightness, z = grid density, w = aspect
      float xform[4];  // x = cos(roll), y = sin(roll), z = pan X, w = pan Y (star coord)
    };
    static_assert(sizeof(SkyboxParams) == 64, "SkyboxParams must match the SkyboxCb cbuffer");

    // First-pass skybox look (tune to taste - these are the knobs for iterating on the
    // background). Deep-space blue fading to near-black, with a sparse scatter of stars.
    constexpr float kSkyTop[3] = {0.020f, 0.028f, 0.070f};
    constexpr float kSkyBottom[3] = {0.000f, 0.002f, 0.020f};
    constexpr float kStarThreshold = 0.985f; // fraction of cells WITHOUT a star (higher = fewer)
    constexpr float kStarBrightness = 0.9f;
    constexpr float kStarDensity = 220.0f;

    // A fixed directional light from the upper-right, angled slightly toward the camera
    // (view space: +z is forward). ambient + diffuse == 1, so a fully-lit face keeps its
    // original palette colour and shadowed faces darken toward 0.4x.
    constexpr float kLightDir[3] = {0.5f, 0.7f, -0.5f};
    constexpr float kAmbient = 0.40f;
    constexpr float kDiffuse = 0.60f;

    // 0xAABBGGRR -> float4 (r,g,b,a) in 0..1.
    void unpackRgba(uint32_t _rgba, float _out[4])
    {
      _out[0] = static_cast<float>(_rgba & 0xFFu) / 255.0f;
      _out[1] = static_cast<float>((_rgba >> 8) & 0xFFu) / 255.0f;
      _out[2] = static_cast<float>((_rgba >> 16) & 0xFFu) / 255.0f;
      _out[3] = static_cast<float>((_rgba >> 24) & 0xFFu) / 255.0f;
    }

    // Resolve a palette index to an opaque RGBA8 (0xAABBGGRR), matching col_rgba.
    uint32_t paletteRgba(int _index)
    {
      Renderer* r = platform_renderer();
      const uint32_t c = r ? r->paletteColour(_index) : 0xFFFFFFFFu;
      return c | 0xFF000000u;
    }
  } // namespace

  void Scene3D::Startup()
  {
    Shutdown(); // resources are created lazily (the device may not be up yet)
  }

  void Scene3D::Shutdown()
  {
    s_vs = nullptr;
    s_ps = nullptr;
    s_layout = nullptr;
    s_cb = nullptr;
    s_depth = nullptr;
    s_raster = nullptr;
    s_blend = nullptr;
    s_bbVs = nullptr;
    s_bbPs = nullptr;
    s_bbVb = nullptr;
    s_bbParamsCb = nullptr;
    s_shipLightCb = nullptr;
    s_skyVs = nullptr;
    s_skyPs = nullptr;
    s_skyCb = nullptr;
    s_skyDepth = nullptr;
    s_dustVs = nullptr;
    s_dustPs = nullptr;
    s_dustLayout = nullptr;
    s_dustVb = nullptr;
    s_dustCapacity = 0;
    s_dust.clear();
    s_meshes.clear();
    s_ready = false;
    // s_provider is set by the game once at startup; keep it across device resets.
  }

  void Scene3D::SetMeshProvider(MeshProvider _provider) { s_provider = std::move(_provider); }

  bool Scene3D::EnsureResources()
  {
    if (s_ready)
      return true;

    ID3D11Device* device = Core::GetD3DDevice();
    if (!device)
      return false;

    check_hresult(device->CreateVertexShader(g_scene3dVS, sizeof(g_scene3dVS), nullptr, s_vs.put()));
    check_hresult(device->CreatePixelShader(g_scene3dPS, sizeof(g_scene3dPS), nullptr, s_ps.put()));

    // Matches MeshVertex { float pos[3]; float nrm[3]; uint32 rgba; } (28 bytes).
    const D3D11_INPUT_ELEMENT_DESC elems[] = {
      {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"NORMAL", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"COLOR", 0, DXGI_FORMAT_R8G8B8A8_UNORM, 0, 24, D3D11_INPUT_PER_VERTEX_DATA, 0},
    };
    check_hresult(device->CreateInputLayout(elems, _countof(elems), g_scene3dVS, sizeof(g_scene3dVS), s_layout.put()));

    D3D11_BUFFER_DESC cbd{};
    cbd.ByteWidth = sizeof(SceneConstants);
    cbd.Usage = D3D11_USAGE_DYNAMIC;
    cbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    cbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    check_hresult(device->CreateBuffer(&cbd, nullptr, s_cb.put()));

    // Depth test + write, LESS_EQUAL: nearest face wins, replacing the painter's sort.
    D3D11_DEPTH_STENCIL_DESC dsd{};
    dsd.DepthEnable = TRUE;
    dsd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ALL;
    dsd.DepthFunc = D3D11_COMPARISON_LESS_EQUAL;
    dsd.StencilEnable = FALSE;
    check_hresult(device->CreateDepthStencilState(&dsd, s_depth.put()));

    // Cull NONE for now: the z-buffer resolves visibility without depending on the
    // legacy face winding, so ships can never come out inside-out. (Enabling backface
    // culling - matching the legacy front-face test - is a later optimisation.)
    D3D11_RASTERIZER_DESC rd{};
    rd.FillMode = D3D11_FILL_SOLID;
    rd.CullMode = D3D11_CULL_NONE;
    rd.DepthClipEnable = TRUE;
    rd.ScissorEnable = FALSE;
    check_hresult(device->CreateRasterizerState(&rd, s_raster.put()));

    // Opaque (no blend): the flat faces fully replace the colour under them.
    D3D11_BLEND_DESC bd{};
    bd.RenderTarget[0].BlendEnable = FALSE;
    bd.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
    check_hresult(device->CreateBlendState(&bd, s_blend.put()));

    // Billboard program (planet/sun) + its dynamic 6-vertex quad and b1 params buffer.
    check_hresult(device->CreateVertexShader(g_scenebbVS, sizeof(g_scenebbVS), nullptr, s_bbVs.put()));
    check_hresult(device->CreatePixelShader(g_scenebbPS, sizeof(g_scenebbPS), nullptr, s_bbPs.put()));

    D3D11_BUFFER_DESC bbvbd{};
    bbvbd.ByteWidth = 6 * sizeof(MeshVertex); // two triangles
    bbvbd.Usage = D3D11_USAGE_DYNAMIC;
    bbvbd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
    bbvbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    check_hresult(device->CreateBuffer(&bbvbd, nullptr, s_bbVb.put()));

    D3D11_BUFFER_DESC bbcbd{};
    bbcbd.ByteWidth = sizeof(BillboardParams);
    bbcbd.Usage = D3D11_USAGE_DYNAMIC;
    bbcbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    bbcbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    check_hresult(device->CreateBuffer(&bbcbd, nullptr, s_bbParamsCb.put()));

    // b2: ship lighting (model-view + directional light). Bound for ship draws only.
    D3D11_BUFFER_DESC lcbd{};
    lcbd.ByteWidth = sizeof(ShipLightConstants);
    lcbd.Usage = D3D11_USAGE_DYNAMIC;
    lcbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    lcbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    check_hresult(device->CreateBuffer(&lcbd, nullptr, s_shipLightCb.put()));

    // Procedural skybox: full-screen-triangle VS (no input layout / vertex buffer) + PS,
    // its b0 params, and a depth-disabled state (it fills the background without touching
    // the depth buffer, so the depth-tested ships draw over it).
    check_hresult(device->CreateVertexShader(g_skyboxVS, sizeof(g_skyboxVS), nullptr, s_skyVs.put()));
    check_hresult(device->CreatePixelShader(g_skyboxPS, sizeof(g_skyboxPS), nullptr, s_skyPs.put()));

    D3D11_BUFFER_DESC skcbd{};
    skcbd.ByteWidth = sizeof(SkyboxParams);
    skcbd.Usage = D3D11_USAGE_DYNAMIC;
    skcbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    skcbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    check_hresult(device->CreateBuffer(&skcbd, nullptr, s_skyCb.put()));

    D3D11_DEPTH_STENCIL_DESC skdsd{};
    skdsd.DepthEnable = FALSE;
    skdsd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
    skdsd.StencilEnable = FALSE;
    check_hresult(device->CreateDepthStencilState(&skdsd, s_skyDepth.put()));

    // Dust program (starfield in the scene pass): pass-through VS + white PS, its own
    // clip-space-XY + brightness input layout. The dynamic vertex buffer is grown lazily
    // in renderDust. Reuses the skybox depth-off state, the cull-none raster and opaque blend.
    check_hresult(device->CreateVertexShader(g_dustVS, sizeof(g_dustVS), nullptr, s_dustVs.put()));
    check_hresult(device->CreatePixelShader(g_dustPS, sizeof(g_dustPS), nullptr, s_dustPs.put()));

    const D3D11_INPUT_ELEMENT_DESC dustElems[] = {
      {"POSITION", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"COLOR", 0, DXGI_FORMAT_R32_FLOAT, 0, 8, D3D11_INPUT_PER_VERTEX_DATA, 0},
    };
    check_hresult(device->CreateInputLayout(dustElems, _countof(dustElems), g_dustVS, sizeof(g_dustVS), s_dustLayout.put()));

    s_ready = true;
    return true;
  }

  const Scene3D::GpuMesh* Scene3D::MeshForType(int _type)
  {
    if (const auto it = s_meshes.find(_type); it != s_meshes.end())
      return &it->second;

    GpuMesh gm; // default: indexCount 0 ("no geometry"), cached so we ask the provider once
    MeshData data;
    if (s_provider && s_provider(_type, data) && !data.vertices.empty() && !data.indices.empty())
    {
      ID3D11Device* device = Core::GetD3DDevice();
      if (device)
      {
        D3D11_BUFFER_DESC vbd{};
        vbd.ByteWidth = static_cast<UINT>(data.vertices.size() * sizeof(MeshVertex));
        vbd.Usage = D3D11_USAGE_IMMUTABLE;
        vbd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
        D3D11_SUBRESOURCE_DATA vsd{};
        vsd.pSysMem = data.vertices.data();

        D3D11_BUFFER_DESC ibd{};
        ibd.ByteWidth = static_cast<UINT>(data.indices.size() * sizeof(uint32_t));
        ibd.Usage = D3D11_USAGE_IMMUTABLE;
        ibd.BindFlags = D3D11_BIND_INDEX_BUFFER;
        D3D11_SUBRESOURCE_DATA isd{};
        isd.pSysMem = data.indices.data();

        if (SUCCEEDED(device->CreateBuffer(&vbd, &vsd, gm.vb.put())) &&
            SUCCEEDED(device->CreateBuffer(&ibd, &isd, gm.ib.put())))
          gm.indexCount = static_cast<UINT>(data.indices.size());
      }
    }

    const auto [it, ok] = s_meshes.emplace(_type, std::move(gm));
    return &it->second;
  }

  void Scene3D::renderSkybox()
  {
    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!ctx)
      return;

    SkyboxParams sp{};
    sp.top[0] = kSkyTop[0]; sp.top[1] = kSkyTop[1]; sp.top[2] = kSkyTop[2]; sp.top[3] = 1.0f;
    sp.bottom[0] = kSkyBottom[0]; sp.bottom[1] = kSkyBottom[1]; sp.bottom[2] = kSkyBottom[2]; sp.bottom[3] = 1.0f;
    sp.params[0] = kStarThreshold;
    sp.params[1] = kStarBrightness;
    sp.params[2] = kStarDensity;
    sp.params[3] = (s_view.height > 0)
                     ? static_cast<float>(s_view.width) / static_cast<float>(s_view.height)
                     : 1.0f; // aspect (w/h), for isotropic star rotation in the shader
    sp.xform[0] = s_skyCos;
    sp.xform[1] = s_skySin;
    sp.xform[2] = s_skyPanX;
    sp.xform[3] = s_skyPanY;

    D3D11_MAPPED_SUBRESOURCE mapped;
    if (FAILED(ctx->Map(s_skyCb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped)))
      return;
    std::memcpy(mapped.pData, &sp, sizeof(sp));
    ctx->Unmap(s_skyCb.get(), 0);

    // Full-screen triangle from SV_VertexID: no input layout / vertex buffer. Depth off
    // (fills the background without touching depth); opaque; cull-none raster.
    ctx->OMSetDepthStencilState(s_skyDepth.get(), 0);
    ctx->RSSetState(s_raster.get());
    const float blendFactor[4] = {0, 0, 0, 0};
    ctx->OMSetBlendState(s_blend.get(), blendFactor, 0xFFFFFFFF);
    ctx->IASetInputLayout(nullptr);
    ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    ID3D11Buffer* noVb = nullptr;
    const UINT zero = 0;
    ctx->IASetVertexBuffers(0, 1, &noVb, &zero, &zero);
    ctx->VSSetShader(s_skyVs.get(), nullptr, 0);
    ctx->PSSetShader(s_skyPs.get(), nullptr, 0);
    ID3D11Buffer* cb = s_skyCb.get();
    ctx->PSSetConstantBuffers(0, 1, &cb);
    ctx->Draw(3, 0);
  }

  void Scene3D::SetDust(const DustVertex* _pts, int _count)
  {
    if (!_pts || _count <= 0)
      s_dust.clear();
    else
      s_dust.assign(_pts, _pts + _count);
  }

  void Scene3D::renderDust()
  {
    if (s_dust.empty())
      return;

    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!ctx)
      return;

    // Grow the dynamic vertex buffer if this frame's dust is bigger than any before it.
    if (s_dust.size() > s_dustCapacity || !s_dustVb)
    {
      s_dustCapacity = s_dust.size() + s_dust.size() / 2 + 64;
      s_dustVb = nullptr;
      D3D11_BUFFER_DESC vbd{};
      vbd.ByteWidth = static_cast<UINT>(s_dustCapacity * sizeof(DustVertex));
      vbd.Usage = D3D11_USAGE_DYNAMIC;
      vbd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
      vbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
      if (FAILED(Core::GetD3DDevice()->CreateBuffer(&vbd, nullptr, s_dustVb.put())))
        return;
    }

    D3D11_MAPPED_SUBRESOURCE mapped;
    if (FAILED(ctx->Map(s_dustVb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped)))
      return;
    std::memcpy(mapped.pData, s_dust.data(), s_dust.size() * sizeof(DustVertex));
    ctx->Unmap(s_dustVb.get(), 0);

    ctx->OMSetDepthStencilState(s_skyDepth.get(), 0); // depth off (over skybox, under ships)
    ctx->RSSetState(s_raster.get());
    const float blendFactor[4] = {0, 0, 0, 0};
    ctx->OMSetBlendState(s_blend.get(), blendFactor, 0xFFFFFFFF);
    ctx->IASetInputLayout(s_dustLayout.get());
    ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    const UINT stride = sizeof(DustVertex);
    const UINT offset = 0;
    ID3D11Buffer* vb = s_dustVb.get();
    ctx->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
    ctx->VSSetShader(s_dustVs.get(), nullptr, 0);
    ctx->PSSetShader(s_dustPs.get(), nullptr, 0);
    ctx->Draw(static_cast<UINT>(s_dust.size()), 0);
  }

  void Scene3D::RenderModels(ID3D11RenderTargetView* _rtv, ID3D11DepthStencilView* _dsv,
                             const Neuron::Client::ViewMetrics& _view, int _vpX, int _vpY, int _vpW, int _vpH,
                             const Neuron::Render::ModelDraw* _models, int _count)
  {
    if (!_rtv || !_dsv || !_models || _count <= 0 || _vpW <= 0 || _vpH <= 0)
      return;
    if (!EnsureResources())
      return;

    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!ctx)
      return;

    // Bind the colour target + depth; clear depth only (colour holds the 2D background).
    ID3D11RenderTargetView* rtvs[1] = {_rtv};
    ctx->OMSetRenderTargets(1, rtvs, _dsv);
    ctx->ClearDepthStencilView(_dsv, D3D11_CLEAR_DEPTH, 1.0f, 0);

    D3D11_VIEWPORT vp{};
    vp.TopLeftX = static_cast<float>(_vpX);
    vp.TopLeftY = static_cast<float>(_vpY);
    vp.Width = static_cast<float>(_vpW);
    vp.Height = static_cast<float>(_vpH);
    vp.MinDepth = 0.0f;
    vp.MaxDepth = 1.0f;
    ctx->RSSetViewports(1, &vp);

    s_view = _view;
    const Neuron::Client::Matrix4 proj = Neuron::Client::MakeScenePerspective(_view, kNearZ, kFarZ);

    // Procedural skybox + streaming dust behind the ships, when enabled. Both are
    // depth-disabled, so they fill the colour buffer without touching the just-cleared
    // depth; the ships draw over them. The shared ship state below overrides their pipeline
    // state before the draw loop.
    if (s_skybox)
    {
      renderSkybox();
      renderDust();
    }

    // Shared pipeline state. The ship + billboard programs use the same input layout,
    // topology, depth, cull and blend; only the shaders + buffers differ per draw.
    ctx->IASetInputLayout(s_layout.get());
    ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    ctx->OMSetDepthStencilState(s_depth.get(), 0);
    ctx->RSSetState(s_raster.get());
    const float blendFactor[4] = {0, 0, 0, 0};
    ctx->OMSetBlendState(s_blend.get(), blendFactor, 0xFFFFFFFF);

    for (int i = 0; i < _count; ++i)
    {
      const Neuron::Render::ModelDraw& m = _models[i];

      // Planet / sun render as depth-tested billboards, not ship meshes.
      if (m.type == kShipPlanet || m.type == kShipSun)
      {
        renderBillboard(m, proj);
        continue;
      }

      const GpuMesh* mesh = MeshForType(m.type);
      if (!mesh || mesh->indexCount == 0)
        continue;

      // Model -> camera: p_cam = transpose(rotmat) * p_model + location, i.e.
      // MV(i,j) = rotmat[j][i] (this reproduces the legacy mult_vector + translate).
      Neuron::Client::Matrix4 mv; // zero
      for (int rr = 0; rr < 3; ++rr)
      {
        for (int cc = 0; cc < 3; ++cc)
          mv(rr, cc) = m.rotmat[cc][rr];
        mv(rr, 3) = m.location[rr];
      }
      mv(3, 3) = 1.0;

      const Neuron::Client::Matrix4 mvp = Neuron::Client::Mul(proj, mv);

      SceneConstants cb{};
      for (int k = 0; k < 16; ++k)
        cb.mvp[k] = static_cast<float>(mvp.m[static_cast<size_t>(k)]);
      // Per-draw colour override is not used by ships (they carry per-face colours);
      // alpha < 0 selects the vertex colour in the shader.
      cb.color[0] = cb.color[1] = cb.color[2] = 0.0f;
      cb.color[3] = -1.0f;

      D3D11_MAPPED_SUBRESOURCE mapped;
      if (FAILED(ctx->Map(s_cb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped)))
        continue;
      std::memcpy(mapped.pData, &cb, sizeof(cb));
      ctx->Unmap(s_cb.get(), 0);

      // b2: model-view (for view-space normals) + the directional light. Always uploaded
      // and bound; when lighting is off, params.x = 0 and the vertex shader skips it, so
      // the flat per-face colour is unchanged.
      ShipLightConstants lc{};
      for (int k = 0; k < 16; ++k)
        lc.mv[k] = static_cast<float>(mv.m[static_cast<size_t>(k)]);
      lc.lightDir[0] = kLightDir[0];
      lc.lightDir[1] = kLightDir[1];
      lc.lightDir[2] = kLightDir[2];
      lc.ambient[0] = lc.ambient[1] = lc.ambient[2] = kAmbient;
      lc.diffuse[0] = lc.diffuse[1] = lc.diffuse[2] = kDiffuse;
      lc.params[0] = s_lit ? 1.0f : 0.0f;

      D3D11_MAPPED_SUBRESOURCE mappedLc;
      if (FAILED(ctx->Map(s_shipLightCb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedLc)))
        continue;
      std::memcpy(mappedLc.pData, &lc, sizeof(lc));
      ctx->Unmap(s_shipLightCb.get(), 0);

      ctx->VSSetShader(s_vs.get(), nullptr, 0);
      ctx->PSSetShader(s_ps.get(), nullptr, 0);
      ID3D11Buffer* cbs[1] = {s_cb.get()};
      ctx->VSSetConstantBuffers(0, 1, cbs);
      ctx->PSSetConstantBuffers(0, 1, cbs);
      ID3D11Buffer* lcb = s_shipLightCb.get();
      ctx->VSSetConstantBuffers(2, 1, &lcb);

      const UINT stride = sizeof(MeshVertex);
      const UINT offset = 0;
      ID3D11Buffer* vb = mesh->vb.get();
      ctx->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
      ctx->IASetIndexBuffer(mesh->ib.get(), DXGI_FORMAT_R32_UINT, 0);
      ctx->DrawIndexed(mesh->indexCount, 0, 0);
    }
  }

  void Scene3D::renderBillboard(const Neuron::Render::ModelDraw& _model, const Neuron::Client::Matrix4& _proj)
  {
    const double cz = _model.location[2];
    if (cz <= 0.0 || _model.distance <= 0.0)
      return; // behind the eye or degenerate

    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!ctx)
      return;

    // On-screen radius in pixels exactly as the legacy draw_planet / draw_sun derived it
    // from the distance + focal length, converted to a world half-size at the billboard
    // depth so the projected quad spans that radius.
    const double radiusPx = (6291456.0 / _model.distance) * (s_view.focal / 256.0);
    const double h = radiusPx * cz / s_view.focal;
    if (h <= 0.0)
      return;

    const float cx = static_cast<float>(_model.location[0]);
    const float cy = static_cast<float>(_model.location[1]);
    const float cf = static_cast<float>(cz);
    const float hf = static_cast<float>(h);

    // Primary colour (planet); the sun is shader-driven, so its vertex colour is unused.
    const uint32_t rgba = (_model.type == kShipSun) ? 0xFFFFFFFFu : paletteRgba(_model.colour);

    // Two camera-space triangles spanning [-h,+h] in x/y at depth cz. The NORMAL slot
    // carries the quad-local uv in [-1,1] for the pixel shader's radius test.
    const MeshVertex quad[6] = {
      {cx - hf, cy - hf, cf, -1.0f, -1.0f, 0.0f, rgba}, {cx + hf, cy - hf, cf, 1.0f, -1.0f, 0.0f, rgba},
      {cx + hf, cy + hf, cf, 1.0f, 1.0f, 0.0f, rgba},   {cx - hf, cy - hf, cf, -1.0f, -1.0f, 0.0f, rgba},
      {cx + hf, cy + hf, cf, 1.0f, 1.0f, 0.0f, rgba},   {cx - hf, cy + hf, cf, -1.0f, 1.0f, 0.0f, rgba},
    };

    D3D11_MAPPED_SUBRESOURCE mappedVb;
    if (FAILED(ctx->Map(s_bbVb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedVb)))
      return;
    std::memcpy(mappedVb.pData, quad, sizeof(quad));
    ctx->Unmap(s_bbVb.get(), 0);

    // b0: u_MVP = projection (corners already in camera space); u_Color unused.
    SceneConstants cb{};
    for (int k = 0; k < 16; ++k)
      cb.mvp[k] = static_cast<float>(_proj.m[static_cast<size_t>(k)]);
    D3D11_MAPPED_SUBRESOURCE mappedCb;
    if (FAILED(ctx->Map(s_cb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedCb)))
      return;
    std::memcpy(mappedCb.pData, &cb, sizeof(cb));
    ctx->Unmap(s_cb.get(), 0);

    // b1: mode + secondary colour. Planet style 0 wireframe->ring, 1 green->disk,
    // 2/3 SNES/fractal->banded; sun -> mode 0.
    BillboardParams bp{};
    int mode = 0;
    if (_model.type == kShipPlanet)
      mode = (_model.style == 0) ? 1 : (_model.style == 1) ? 2 : 3;
    bp.params[0] = static_cast<float>(mode);
    if (mode == 3 && _model.colour2 >= 0)
      unpackRgba(paletteRgba(_model.colour2), bp.colorB);

    D3D11_MAPPED_SUBRESOURCE mappedBp;
    if (FAILED(ctx->Map(s_bbParamsCb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedBp)))
      return;
    std::memcpy(mappedBp.pData, &bp, sizeof(bp));
    ctx->Unmap(s_bbParamsCb.get(), 0);

    ctx->VSSetShader(s_bbVs.get(), nullptr, 0);
    ctx->PSSetShader(s_bbPs.get(), nullptr, 0);
    ID3D11Buffer* cb0 = s_cb.get();
    ID3D11Buffer* cb1 = s_bbParamsCb.get();
    ctx->VSSetConstantBuffers(0, 1, &cb0);
    ctx->PSSetConstantBuffers(1, 1, &cb1);

    const UINT stride = sizeof(MeshVertex);
    const UINT offset = 0;
    ID3D11Buffer* vb = s_bbVb.get();
    ctx->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
    ctx->Draw(6, 0);
  }
}
