#include "pch.h"
#include "Scene3D.h"

#include <cstring>
#include <utility>

#include "SceneProjection.h"

// Offline-compiled (fxc) byte arrays, generated by the CMake build into
// shaders/CompiledShaders/ (on this target's private include path), same as Render2D.
#include "scene3dPS.h" // g_scene3dPS
#include "scene3dVS.h" // g_scene3dVS

using winrt::com_ptr;
using winrt::check_hresult;

namespace Neuron::Graphics
{
  namespace
  {
    // Depth range for the flight scene. Near just in front of the eye (the legacy path
    // clamped z <= 0 to 1); far past the ship cull distance (space.cpp removes ships at
    // distance > 57344). D32_FLOAT keeps ample precision across this range.
    constexpr float kNearZ = 1.0f;
    constexpr float kFarZ = 131072.0f;

    // Mirrors SceneCb in shaders/partials/scene3d.hlsli (row-major mvp + flat tint).
    struct SceneConstants
    {
      float mvp[16];
      float color[4];
    };
    static_assert(sizeof(SceneConstants) == 80, "SceneConstants must match the SceneCb cbuffer");
  } // namespace

  void Scene3D::Startup()
  {
    Shutdown(); // resources are created lazily (the device may not be up yet)
  }

  void Scene3D::Shutdown()
  {
    s_vs = nullptr;
    s_ps = nullptr;
    s_layout = nullptr;
    s_cb = nullptr;
    s_depth = nullptr;
    s_raster = nullptr;
    s_blend = nullptr;
    s_meshes.clear();
    s_ready = false;
    // s_provider is set by the game once at startup; keep it across device resets.
  }

  void Scene3D::SetMeshProvider(MeshProvider _provider) { s_provider = std::move(_provider); }

  bool Scene3D::EnsureResources()
  {
    if (s_ready)
      return true;

    ID3D11Device* device = Core::GetD3DDevice();
    if (!device)
      return false;

    check_hresult(device->CreateVertexShader(g_scene3dVS, sizeof(g_scene3dVS), nullptr, s_vs.put()));
    check_hresult(device->CreatePixelShader(g_scene3dPS, sizeof(g_scene3dPS), nullptr, s_ps.put()));

    // Matches MeshVertex { float pos[3]; float nrm[3]; uint32 rgba; } (28 bytes).
    const D3D11_INPUT_ELEMENT_DESC elems[] = {
      {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"NORMAL", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"COLOR", 0, DXGI_FORMAT_R8G8B8A8_UNORM, 0, 24, D3D11_INPUT_PER_VERTEX_DATA, 0},
    };
    check_hresult(device->CreateInputLayout(elems, _countof(elems), g_scene3dVS, sizeof(g_scene3dVS), s_layout.put()));

    D3D11_BUFFER_DESC cbd{};
    cbd.ByteWidth = sizeof(SceneConstants);
    cbd.Usage = D3D11_USAGE_DYNAMIC;
    cbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    cbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    check_hresult(device->CreateBuffer(&cbd, nullptr, s_cb.put()));

    // Depth test + write, LESS_EQUAL: nearest face wins, replacing the painter's sort.
    D3D11_DEPTH_STENCIL_DESC dsd{};
    dsd.DepthEnable = TRUE;
    dsd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ALL;
    dsd.DepthFunc = D3D11_COMPARISON_LESS_EQUAL;
    dsd.StencilEnable = FALSE;
    check_hresult(device->CreateDepthStencilState(&dsd, s_depth.put()));

    // Cull NONE for now: the z-buffer resolves visibility without depending on the
    // legacy face winding, so ships can never come out inside-out. (Enabling backface
    // culling - matching the legacy front-face test - is a later optimisation.)
    D3D11_RASTERIZER_DESC rd{};
    rd.FillMode = D3D11_FILL_SOLID;
    rd.CullMode = D3D11_CULL_NONE;
    rd.DepthClipEnable = TRUE;
    rd.ScissorEnable = FALSE;
    check_hresult(device->CreateRasterizerState(&rd, s_raster.put()));

    // Opaque (no blend): the flat faces fully replace the colour under them.
    D3D11_BLEND_DESC bd{};
    bd.RenderTarget[0].BlendEnable = FALSE;
    bd.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
    check_hresult(device->CreateBlendState(&bd, s_blend.put()));

    s_ready = true;
    return true;
  }

  const Scene3D::GpuMesh* Scene3D::MeshForType(int _type)
  {
    if (const auto it = s_meshes.find(_type); it != s_meshes.end())
      return &it->second;

    GpuMesh gm; // default: indexCount 0 ("no geometry"), cached so we ask the provider once
    MeshData data;
    if (s_provider && s_provider(_type, data) && !data.vertices.empty() && !data.indices.empty())
    {
      ID3D11Device* device = Core::GetD3DDevice();
      if (device)
      {
        D3D11_BUFFER_DESC vbd{};
        vbd.ByteWidth = static_cast<UINT>(data.vertices.size() * sizeof(MeshVertex));
        vbd.Usage = D3D11_USAGE_IMMUTABLE;
        vbd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
        D3D11_SUBRESOURCE_DATA vsd{};
        vsd.pSysMem = data.vertices.data();

        D3D11_BUFFER_DESC ibd{};
        ibd.ByteWidth = static_cast<UINT>(data.indices.size() * sizeof(uint32_t));
        ibd.Usage = D3D11_USAGE_IMMUTABLE;
        ibd.BindFlags = D3D11_BIND_INDEX_BUFFER;
        D3D11_SUBRESOURCE_DATA isd{};
        isd.pSysMem = data.indices.data();

        if (SUCCEEDED(device->CreateBuffer(&vbd, &vsd, gm.vb.put())) &&
            SUCCEEDED(device->CreateBuffer(&ibd, &isd, gm.ib.put())))
          gm.indexCount = static_cast<UINT>(data.indices.size());
      }
    }

    const auto [it, ok] = s_meshes.emplace(_type, std::move(gm));
    return &it->second;
  }

  void Scene3D::RenderModels(ID3D11RenderTargetView* _rtv, ID3D11DepthStencilView* _dsv,
                             const Neuron::Client::ViewMetrics& _view, int _vpX, int _vpY, int _vpW, int _vpH,
                             const Neuron::Render::ModelDraw* _models, int _count)
  {
    if (!_rtv || !_dsv || !_models || _count <= 0 || _vpW <= 0 || _vpH <= 0)
      return;
    if (!EnsureResources())
      return;

    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!ctx)
      return;

    // Bind the colour target + depth; clear depth only (colour holds the 2D background).
    ID3D11RenderTargetView* rtvs[1] = {_rtv};
    ctx->OMSetRenderTargets(1, rtvs, _dsv);
    ctx->ClearDepthStencilView(_dsv, D3D11_CLEAR_DEPTH, 1.0f, 0);

    D3D11_VIEWPORT vp{};
    vp.TopLeftX = static_cast<float>(_vpX);
    vp.TopLeftY = static_cast<float>(_vpY);
    vp.Width = static_cast<float>(_vpW);
    vp.Height = static_cast<float>(_vpH);
    vp.MinDepth = 0.0f;
    vp.MaxDepth = 1.0f;
    ctx->RSSetViewports(1, &vp);

    const Neuron::Client::Matrix4 proj = Neuron::Client::MakeScenePerspective(_view, kNearZ, kFarZ);

    ctx->IASetInputLayout(s_layout.get());
    ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    ctx->VSSetShader(s_vs.get(), nullptr, 0);
    ctx->PSSetShader(s_ps.get(), nullptr, 0);
    ctx->OMSetDepthStencilState(s_depth.get(), 0);
    ctx->RSSetState(s_raster.get());
    const float blendFactor[4] = {0, 0, 0, 0};
    ctx->OMSetBlendState(s_blend.get(), blendFactor, 0xFFFFFFFF);

    for (int i = 0; i < _count; ++i)
    {
      const Neuron::Render::ModelDraw& m = _models[i];
      const GpuMesh* mesh = MeshForType(m.type);
      if (!mesh || mesh->indexCount == 0)
        continue;

      // Model -> camera: p_cam = transpose(rotmat) * p_model + location, i.e.
      // MV(i,j) = rotmat[j][i] (this reproduces the legacy mult_vector + translate).
      Neuron::Client::Matrix4 mv; // zero
      for (int rr = 0; rr < 3; ++rr)
      {
        for (int cc = 0; cc < 3; ++cc)
          mv(rr, cc) = m.rotmat[cc][rr];
        mv(rr, 3) = m.location[rr];
      }
      mv(3, 3) = 1.0;

      const Neuron::Client::Matrix4 mvp = Neuron::Client::Mul(proj, mv);

      SceneConstants cb{};
      for (int k = 0; k < 16; ++k)
        cb.mvp[k] = static_cast<float>(mvp.m[static_cast<size_t>(k)]);
      // Per-draw colour override is not used by ships (they carry per-face colours);
      // alpha < 0 selects the vertex colour in the shader.
      cb.color[0] = cb.color[1] = cb.color[2] = 0.0f;
      cb.color[3] = -1.0f;

      D3D11_MAPPED_SUBRESOURCE mapped;
      if (FAILED(ctx->Map(s_cb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped)))
        continue;
      std::memcpy(mapped.pData, &cb, sizeof(cb));
      ctx->Unmap(s_cb.get(), 0);

      ID3D11Buffer* cbs[1] = {s_cb.get()};
      ctx->VSSetConstantBuffers(0, 1, cbs);
      ctx->PSSetConstantBuffers(0, 1, cbs);

      const UINT stride = sizeof(MeshVertex);
      const UINT offset = 0;
      ID3D11Buffer* vb = mesh->vb.get();
      ctx->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
      ctx->IASetIndexBuffer(mesh->ib.get(), DXGI_FORMAT_R32_UINT, 0);
      ctx->DrawIndexed(mesh->indexCount, 0, 0);
    }
  }
}
