#include "pch.h"
#include "Scene3D.h"

#include <cstring>
#include <utility>

#include "Renderer.h"        // platform_renderer() -> master palette (planet/sun billboard colours)

// Offline-compiled (fxc) byte arrays, generated by the CMake build into
// shaders/CompiledShaders/ (on this target's private include path), same as Render2D.
#include "scene3dPS.h" // g_scene3dPS
#include "scene3dVS.h" // g_scene3dVS
#include "scenebbPS.h" // g_scenebbPS - planet/sun billboard pixel shader
#include "scenebbVS.h" // g_scenebbVS - planet/sun billboard vertex shader
#include "dustPS.h"    // g_dustPS    - dust points (starfield in the scene pass)
#include "dustVS.h"    // g_dustVS

using winrt::com_ptr;
using winrt::check_hresult;
using namespace DirectX;

namespace Neuron::Graphics
{
  namespace
  {
    // The sun object type (drawn as a billboard, not a ship mesh). The planet (-1) is a real
    // sphere mesh now, so it goes through the normal mesh path keyed by its type.
    constexpr int kShipSun = -2;

    // Mirrors SceneCb in shaders/partials/scene3d.hlsli (row-major mvp + flat tint).
    struct SceneConstants
    {
      float mvp[16];
      float color[4];
    };
    static_assert(sizeof(SceneConstants) == 80, "SceneConstants must match the SceneCb cbuffer");

    // Mirrors BillboardCb in shaders/partials/scenebb.hlsli (secondary colour + params).
    struct BillboardParams
    {
      float colorB[4];
      float params[4]; // x = mode (0 sun, 1 ring, 2 disk, 3 banded)
    };
    static_assert(sizeof(BillboardParams) == 32, "BillboardParams must match the BillboardCb cbuffer");

    // Mirrors ShipLightCb in shaders/partials/scene3d.hlsli (model-view + directional
    // light). Ship-only (b2); billboards do not use it.
    struct ShipLightConstants
    {
      float mv[16];
      float lightDir[4];
      float ambient[4];
      float diffuse[4];
      float params[4]; // x = lit (0 / 1)
    };
    static_assert(sizeof(ShipLightConstants) == 128, "ShipLightConstants must match the ShipLightCb cbuffer");

    // A fixed directional light from the upper-right, angled slightly toward the camera
    // (view space: +z is forward). ambient + diffuse == 1, so a fully-lit face keeps its
    // original palette colour and shadowed faces darken toward 0.4x.
    constexpr float kLightDir[3] = {0.5f, 0.7f, -0.5f};
    constexpr float kAmbient = 0.40f;
    constexpr float kDiffuse = 0.60f;

    // Resolve a palette index to an opaque RGBA8 (0xAABBGGRR), matching col_rgba.
    uint32_t paletteRgba(int _index)
    {
      Renderer* r = platform_renderer();
      const uint32_t c = r ? r->paletteColour(_index) : 0xFFFFFFFFu;
      return c | 0xFF000000u;
    }
  } // namespace

  void Scene3D::Startup()
  {
    Shutdown(); // resources are created lazily (the device may not be up yet)
  }

  void Scene3D::Shutdown()
  {
    s_vs = nullptr;
    s_ps = nullptr;
    s_layout = nullptr;
    s_cb = nullptr;
    s_depth = nullptr;
    s_raster = nullptr;
    s_blend = nullptr;
    s_bbVs = nullptr;
    s_bbPs = nullptr;
    s_bbVb = nullptr;
    s_bbParamsCb = nullptr;
    s_shipLightCb = nullptr;
    s_dustVs = nullptr;
    s_dustPs = nullptr;
    s_dustLayout = nullptr;
    s_dustVb = nullptr;
    s_dustDepth = nullptr;
    s_dustCapacity = 0;
    s_dust.clear();
    s_models.clear();
    s_meshes.clear();
    s_ready = false;
    // s_provider is set by the game once at startup; keep it across device resets.
  }

  void Scene3D::SetMeshProvider(MeshProvider _provider) { s_provider = std::move(_provider); }

  bool Scene3D::EnsureResources()
  {
    if (s_ready)
      return true;

    ID3D11Device* device = Core::GetD3DDevice();
    if (!device)
      return false;

    check_hresult(device->CreateVertexShader(g_scene3dVS, sizeof(g_scene3dVS), nullptr, s_vs.put()));
    check_hresult(device->CreatePixelShader(g_scene3dPS, sizeof(g_scene3dPS), nullptr, s_ps.put()));

    // Matches MeshVertex { float pos[3]; float nrm[3]; uint32 rgba; } (28 bytes).
    const D3D11_INPUT_ELEMENT_DESC elems[] = {
      {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"NORMAL", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"COLOR", 0, DXGI_FORMAT_R8G8B8A8_UNORM, 0, 24, D3D11_INPUT_PER_VERTEX_DATA, 0},
    };
    check_hresult(device->CreateInputLayout(elems, _countof(elems), g_scene3dVS, sizeof(g_scene3dVS), s_layout.put()));

    D3D11_BUFFER_DESC cbd{};
    cbd.ByteWidth = sizeof(SceneConstants);
    cbd.Usage = D3D11_USAGE_DYNAMIC;
    cbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    cbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    check_hresult(device->CreateBuffer(&cbd, nullptr, s_cb.put()));

    // Depth test + write, LESS_EQUAL: nearest face wins, replacing the painter's sort.
    D3D11_DEPTH_STENCIL_DESC dsd{};
    dsd.DepthEnable = TRUE;
    dsd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ALL;
    dsd.DepthFunc = D3D11_COMPARISON_LESS_EQUAL;
    dsd.StencilEnable = FALSE;
    check_hresult(device->CreateDepthStencilState(&dsd, s_depth.put()));

    // Cull NONE for now: the z-buffer resolves visibility without depending on the
    // legacy face winding, so ships can never come out inside-out. (Enabling backface
    // culling - matching the legacy front-face test - is a later optimisation.)
    D3D11_RASTERIZER_DESC rd{};
    rd.FillMode = D3D11_FILL_SOLID;
    rd.CullMode = D3D11_CULL_NONE;
    rd.DepthClipEnable = TRUE;
    rd.ScissorEnable = FALSE;
    check_hresult(device->CreateRasterizerState(&rd, s_raster.put()));

    // Opaque (no blend): the flat faces fully replace the colour under them.
    D3D11_BLEND_DESC bd{};
    bd.RenderTarget[0].BlendEnable = FALSE;
    bd.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
    check_hresult(device->CreateBlendState(&bd, s_blend.put()));

    // Billboard program (planet/sun) + its dynamic 6-vertex quad and b1 params buffer.
    check_hresult(device->CreateVertexShader(g_scenebbVS, sizeof(g_scenebbVS), nullptr, s_bbVs.put()));
    check_hresult(device->CreatePixelShader(g_scenebbPS, sizeof(g_scenebbPS), nullptr, s_bbPs.put()));

    D3D11_BUFFER_DESC bbvbd{};
    bbvbd.ByteWidth = 6 * sizeof(MeshVertex); // two triangles
    bbvbd.Usage = D3D11_USAGE_DYNAMIC;
    bbvbd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
    bbvbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    check_hresult(device->CreateBuffer(&bbvbd, nullptr, s_bbVb.put()));

    D3D11_BUFFER_DESC bbcbd{};
    bbcbd.ByteWidth = sizeof(BillboardParams);
    bbcbd.Usage = D3D11_USAGE_DYNAMIC;
    bbcbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    bbcbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    check_hresult(device->CreateBuffer(&bbcbd, nullptr, s_bbParamsCb.put()));

    // b2: ship lighting (model-view + directional light). Bound for ship draws only.
    D3D11_BUFFER_DESC lcbd{};
    lcbd.ByteWidth = sizeof(ShipLightConstants);
    lcbd.Usage = D3D11_USAGE_DYNAMIC;
    lcbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    lcbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    check_hresult(device->CreateBuffer(&lcbd, nullptr, s_shipLightCb.put()));

    // Depth-disabled state for the background dust pass: it fills the colour buffer without
    // touching the just-cleared depth, so the depth-tested ships draw over it.
    D3D11_DEPTH_STENCIL_DESC bgdsd{};
    bgdsd.DepthEnable = FALSE;
    bgdsd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
    bgdsd.StencilEnable = FALSE;
    check_hresult(device->CreateDepthStencilState(&bgdsd, s_dustDepth.put()));

    // Dust program (the streaming starfield in the scene pass): pass-through VS + white PS, its
    // own clip-space-XY + brightness input layout. The dynamic vertex buffer is grown lazily in
    // renderDust. Shares the depth-off state above, the cull-none raster and opaque blend.
    check_hresult(device->CreateVertexShader(g_dustVS, sizeof(g_dustVS), nullptr, s_dustVs.put()));
    check_hresult(device->CreatePixelShader(g_dustPS, sizeof(g_dustPS), nullptr, s_dustPs.put()));

    const D3D11_INPUT_ELEMENT_DESC dustElems[] = {
      {"POSITION", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0},
      {"COLOR", 0, DXGI_FORMAT_R32_FLOAT, 0, 8, D3D11_INPUT_PER_VERTEX_DATA, 0},
    };
    check_hresult(device->CreateInputLayout(dustElems, _countof(dustElems), g_dustVS, sizeof(g_dustVS), s_dustLayout.put()));

    s_ready = true;
    return true;
  }

  const Scene3D::GpuMesh* Scene3D::MeshForType(int _type)
  {
    if (const auto it = s_meshes.find(_type); it != s_meshes.end())
      return &it->second;

    GpuMesh gm; // default: indexCount 0 ("no geometry"), cached so we ask the provider once
    MeshData data;
    if (s_provider && s_provider(_type, data) && !data.vertices.empty() && !data.indices.empty())
    {
      ID3D11Device* device = Core::GetD3DDevice();
      if (device)
      {
        D3D11_BUFFER_DESC vbd{};
        vbd.ByteWidth = static_cast<UINT>(data.vertices.size() * sizeof(MeshVertex));
        vbd.Usage = D3D11_USAGE_IMMUTABLE;
        vbd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
        D3D11_SUBRESOURCE_DATA vsd{};
        vsd.pSysMem = data.vertices.data();

        D3D11_BUFFER_DESC ibd{};
        ibd.ByteWidth = static_cast<UINT>(data.indices.size() * sizeof(uint32_t));
        ibd.Usage = D3D11_USAGE_IMMUTABLE;
        ibd.BindFlags = D3D11_BIND_INDEX_BUFFER;
        D3D11_SUBRESOURCE_DATA isd{};
        isd.pSysMem = data.indices.data();

        if (SUCCEEDED(device->CreateBuffer(&vbd, &vsd, gm.vb.put())) &&
            SUCCEEDED(device->CreateBuffer(&ibd, &isd, gm.ib.put())))
          gm.indexCount = static_cast<UINT>(data.indices.size());
      }
    }

    const auto [it, ok] = s_meshes.emplace(_type, std::move(gm));
    return &it->second;
  }

  void Scene3D::SetDust(const DustVertex* _pts, int _count)
  {
    if (!_pts || _count <= 0)
      s_dust.clear();
    else
      s_dust.assign(_pts, _pts + _count);
  }

  void Scene3D::renderDust()
  {
    if (s_dust.empty())
      return;

    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!ctx)
      return;

    // Grow the dynamic vertex buffer if this frame's dust is bigger than any before it.
    if (s_dust.size() > s_dustCapacity || !s_dustVb)
    {
      s_dustCapacity = s_dust.size() + s_dust.size() / 2 + 64;
      s_dustVb = nullptr;
      D3D11_BUFFER_DESC vbd{};
      vbd.ByteWidth = static_cast<UINT>(s_dustCapacity * sizeof(DustVertex));
      vbd.Usage = D3D11_USAGE_DYNAMIC;
      vbd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
      vbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
      if (FAILED(Core::GetD3DDevice()->CreateBuffer(&vbd, nullptr, s_dustVb.put())))
        return;
    }

    D3D11_MAPPED_SUBRESOURCE mapped;
    if (FAILED(ctx->Map(s_dustVb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped)))
      return;
    std::memcpy(mapped.pData, s_dust.data(), s_dust.size() * sizeof(DustVertex));
    ctx->Unmap(s_dustVb.get(), 0);

    ctx->OMSetDepthStencilState(s_dustDepth.get(), 0); // depth off (background pass, under ships)
    ctx->RSSetState(s_raster.get());
    const float blendFactor[4] = {0, 0, 0, 0};
    ctx->OMSetBlendState(s_blend.get(), blendFactor, 0xFFFFFFFF);
    ctx->IASetInputLayout(s_dustLayout.get());
    ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    const UINT stride = sizeof(DustVertex);
    const UINT offset = 0;
    ID3D11Buffer* vb = s_dustVb.get();
    ctx->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
    ctx->VSSetShader(s_dustVs.get(), nullptr, 0);
    ctx->PSSetShader(s_dustPs.get(), nullptr, 0);
    ctx->Draw(static_cast<UINT>(s_dust.size()), 0);
  }

  void Scene3D::SubmitModel(const Neuron::Render::ModelDraw& _model) { s_models.push_back(_model); }

  void Scene3D::RenderModels(ID3D11RenderTargetView* _rtv, ID3D11DepthStencilView* _dsv,
                             Neuron::Client::Camera& _camera, int _vpX, int _vpY, int _vpW, int _vpH)
  {
    // This frame's submitted models (SubmitModel, straight from the game's draw pass) are
    // consumed and cleared here - every exit path clears s_models so nothing carries into the
    // next frame. The scene pass owns the background (the streaming dust starfield), so it runs
    // even with no models this frame - staring at empty space must still show the stars.
    if (!_rtv || !_dsv || _vpW <= 0 || _vpH <= 0)
    {
      s_models.clear();
      return;
    }
    if (!EnsureResources())
    {
      s_models.clear();
      return;
    }

    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!ctx)
    {
      s_models.clear();
      return;
    }

    // Bind the colour target + depth; clear depth only (colour holds the 2D background).
    ID3D11RenderTargetView* rtvs[1] = {_rtv};
    ctx->OMSetRenderTargets(1, rtvs, _dsv);
    ctx->ClearDepthStencilView(_dsv, D3D11_CLEAR_DEPTH, 1.0f, 0);

    D3D11_VIEWPORT vp{};
    vp.TopLeftX = static_cast<float>(_vpX);
    vp.TopLeftY = static_cast<float>(_vpY);
    vp.Width = static_cast<float>(_vpW);
    vp.Height = static_cast<float>(_vpH);
    vp.MinDepth = 0.0f;
    vp.MaxDepth = 1.0f;
    ctx->RSSetViewports(1, &vp);

    // The pass's view + projection, straight from the Camera. Row-vector DirectXMath
    // matrices (p' = p * M); the shaders consume column-vector matrices stored
    // row-major (mul(u_MVP, pos)), so every upload below is the transpose.
    const XMMATRIX view = _camera.View();
    const XMMATRIX proj = _camera.Projection();
    XMStoreFloat4x4(&s_viewMat, view);
    XMStoreFloat4x4(&s_projMat, proj);

    // Streaming dust (the starfield) behind the ships. Depth-disabled, so it fills the colour
    // buffer without touching the just-cleared depth; the ships draw over it. Drawn before the
    // model-count check so the background shows even in empty space.
    renderDust();

    // Nothing else to draw this frame (no ships / planet / sun in view): the background above
    // is the whole scene, so skip the ship pipeline setup.
    if (s_models.empty())
      return;

    const XMMATRIX viewProj = XMMatrixMultiply(view, proj);

    // Shared pipeline state. The ship + billboard programs use the same input layout,
    // topology, depth, cull and blend; only the shaders + buffers differ per draw.
    ctx->IASetInputLayout(s_layout.get());
    ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    ctx->OMSetDepthStencilState(s_depth.get(), 0);
    ctx->RSSetState(s_raster.get());
    const float blendFactor[4] = {0, 0, 0, 0};
    ctx->OMSetBlendState(s_blend.get(), blendFactor, 0xFFFFFFFF);

    for (const Neuron::Render::ModelDraw& m : s_models)
    {
      // The sun renders as a depth-tested billboard (a glowing radial-gradient disk). The
      // planet is now a real sphere mesh, so it falls through to the ship mesh path below.
      if (m.type == kShipSun)
      {
        renderBillboard(m);
        continue;
      }

      const GpuMesh* mesh = MeshForType(m.type);
      if (!mesh || mesh->indexCount == 0)
        continue;

      // Model -> world: the record's basis rows (side/roof/nose) ARE the rows of the
      // row-vector world matrix, with the floating-origin-relative position in row 3
      // (p_world = p_model * W reproduces the legacy transpose(rotmat) + translate).
      const XMMATRIX world = XMMatrixSet(
          static_cast<float>(m.rotmat[0][0]), static_cast<float>(m.rotmat[0][1]), static_cast<float>(m.rotmat[0][2]), 0.0f,
          static_cast<float>(m.rotmat[1][0]), static_cast<float>(m.rotmat[1][1]), static_cast<float>(m.rotmat[1][2]), 0.0f,
          static_cast<float>(m.rotmat[2][0]), static_cast<float>(m.rotmat[2][1]), static_cast<float>(m.rotmat[2][2]), 0.0f,
          static_cast<float>(m.location[0]), static_cast<float>(m.location[1]), static_cast<float>(m.location[2]), 1.0f);

      const XMMATRIX mv = XMMatrixMultiply(world, view);
      const XMMATRIX mvp = XMMatrixMultiply(world, viewProj);

      SceneConstants cb{};
      XMFLOAT4X4 mvpT;
      XMStoreFloat4x4(&mvpT, XMMatrixTranspose(mvp));
      std::memcpy(cb.mvp, &mvpT, sizeof(cb.mvp));
      // Per-draw colour override is not used by ships (they carry per-face colours);
      // alpha < 0 selects the vertex colour in the shader.
      cb.color[0] = cb.color[1] = cb.color[2] = 0.0f;
      cb.color[3] = -1.0f;

      D3D11_MAPPED_SUBRESOURCE mapped;
      if (FAILED(ctx->Map(s_cb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped)))
        continue;
      std::memcpy(mapped.pData, &cb, sizeof(cb));
      ctx->Unmap(s_cb.get(), 0);

      // b2: model-view (for view-space normals) + the directional light. Always uploaded
      // and bound; when lighting is off, params.x = 0 and the vertex shader skips it, so
      // the flat per-face colour is unchanged.
      ShipLightConstants lc{};
      XMFLOAT4X4 mvT;
      XMStoreFloat4x4(&mvT, XMMatrixTranspose(mv));
      std::memcpy(lc.mv, &mvT, sizeof(lc.mv));
      lc.lightDir[0] = kLightDir[0];
      lc.lightDir[1] = kLightDir[1];
      lc.lightDir[2] = kLightDir[2];
      lc.ambient[0] = lc.ambient[1] = lc.ambient[2] = kAmbient;
      lc.diffuse[0] = lc.diffuse[1] = lc.diffuse[2] = kDiffuse;
      lc.params[0] = s_lit ? 1.0f : 0.0f;

      D3D11_MAPPED_SUBRESOURCE mappedLc;
      if (FAILED(ctx->Map(s_shipLightCb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedLc)))
        continue;
      std::memcpy(mappedLc.pData, &lc, sizeof(lc));
      ctx->Unmap(s_shipLightCb.get(), 0);

      ctx->VSSetShader(s_vs.get(), nullptr, 0);
      ctx->PSSetShader(s_ps.get(), nullptr, 0);
      ID3D11Buffer* cbs[1] = {s_cb.get()};
      ctx->VSSetConstantBuffers(0, 1, cbs);
      ctx->PSSetConstantBuffers(0, 1, cbs);
      ID3D11Buffer* lcb = s_shipLightCb.get();
      ctx->VSSetConstantBuffers(2, 1, &lcb);

      const UINT stride = sizeof(MeshVertex);
      const UINT offset = 0;
      ID3D11Buffer* vb = mesh->vb.get();
      ctx->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
      ctx->IASetIndexBuffer(mesh->ib.get(), DXGI_FORMAT_R32_UINT, 0);
      ctx->DrawIndexed(mesh->indexCount, 0, 0);
    }

    s_models.clear();
  }

  void Scene3D::renderBillboard(const Neuron::Render::ModelDraw& _model)
  {
    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!ctx)
      return;

    // World-frame centre -> camera space through the pass's view matrix; the quad is
    // then built camera-facing at that depth and drawn with the projection alone.
    const XMVECTOR camC = XMVector3TransformCoord(
        XMVectorSet(static_cast<float>(_model.location[0]), static_cast<float>(_model.location[1]),
                    static_cast<float>(_model.location[2]), 1.0f),
        XMLoadFloat4x4(&s_viewMat));

    const double cz = static_cast<double>(XMVectorGetZ(camC));
    if (cz <= 0.0 || _model.distance <= 0.0)
      return; // behind the eye or degenerate

    // Camera-space half-size that projects to the legacy on-screen radius: the old
    // form was radiusPx = (6291456 / distance) * (focal / 256) and h = radiusPx * z /
    // focal - the focal length cancels, so the size is optics-independent.
    const double h = (6291456.0 / 256.0) * cz / _model.distance;
    if (h <= 0.0)
      return;

    const float cx = XMVectorGetX(camC);
    const float cy = XMVectorGetY(camC);
    const float cf = static_cast<float>(cz);
    const float hf = static_cast<float>(h);

    // Primary colour (planet); the sun is shader-driven, so its vertex colour is unused.
    const uint32_t rgba = (_model.type == kShipSun) ? 0xFFFFFFFFu : paletteRgba(_model.colour);

    // Two camera-space triangles spanning [-h,+h] in x/y at depth cz. The NORMAL slot
    // carries the quad-local uv in [-1,1] for the pixel shader's radius test.
    const MeshVertex quad[6] = {
      {cx - hf, cy - hf, cf, -1.0f, -1.0f, 0.0f, rgba}, {cx + hf, cy - hf, cf, 1.0f, -1.0f, 0.0f, rgba},
      {cx + hf, cy + hf, cf, 1.0f, 1.0f, 0.0f, rgba},   {cx - hf, cy - hf, cf, -1.0f, -1.0f, 0.0f, rgba},
      {cx + hf, cy + hf, cf, 1.0f, 1.0f, 0.0f, rgba},   {cx - hf, cy + hf, cf, -1.0f, 1.0f, 0.0f, rgba},
    };

    D3D11_MAPPED_SUBRESOURCE mappedVb;
    if (FAILED(ctx->Map(s_bbVb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedVb)))
      return;
    std::memcpy(mappedVb.pData, quad, sizeof(quad));
    ctx->Unmap(s_bbVb.get(), 0);

    // b0: u_MVP = projection (corners already in camera space); u_Color unused. The
    // shader wants the column-vector matrix stored row-major -> upload the transpose.
    SceneConstants cb{};
    XMFLOAT4X4 projT;
    XMStoreFloat4x4(&projT, XMMatrixTranspose(XMLoadFloat4x4(&s_projMat)));
    std::memcpy(cb.mvp, &projT, sizeof(cb.mvp));
    D3D11_MAPPED_SUBRESOURCE mappedCb;
    if (FAILED(ctx->Map(s_cb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedCb)))
      return;
    std::memcpy(mappedCb.pData, &cb, sizeof(cb));
    ctx->Unmap(s_cb.get(), 0);

    // b1: billboard mode. The sun is the only billboard now (mode 0 - the shader's
    // white->yellow->orange radial gradient); the planet migrated to a real sphere mesh, so
    // the old planet ring/disk/band billboard modes are gone.
    BillboardParams bp{};
    bp.params[0] = 0.0f;

    D3D11_MAPPED_SUBRESOURCE mappedBp;
    if (FAILED(ctx->Map(s_bbParamsCb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedBp)))
      return;
    std::memcpy(mappedBp.pData, &bp, sizeof(bp));
    ctx->Unmap(s_bbParamsCb.get(), 0);

    ctx->VSSetShader(s_bbVs.get(), nullptr, 0);
    ctx->PSSetShader(s_bbPs.get(), nullptr, 0);
    ID3D11Buffer* cb0 = s_cb.get();
    ID3D11Buffer* cb1 = s_bbParamsCb.get();
    ctx->VSSetConstantBuffers(0, 1, &cb0);
    ctx->PSSetConstantBuffers(1, 1, &cb1);

    const UINT stride = sizeof(MeshVertex);
    const UINT offset = 0;
    ID3D11Buffer* vb = s_bbVb.get();
    ctx->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
    ctx->Draw(6, 0);
  }
}
