#include "pch.h"
#include "SceneGlow.h"

#include <cstring>

// Offline-compiled (fxc) byte arrays for the post chain, generated by the CMake build
// into shaders/CompiledShaders/ (this target's private include path).
#include "postVS.h"      // g_postVS      - full-screen triangle (SV_VertexID, no vertex buffer)
#include "blurPS.h"      // g_blurPS      - separable Gaussian (radius-4, one axis per pass)
#include "compositePS.h" // g_compositePS - sharp + glow*intensity

using winrt::com_ptr;
using winrt::check_hresult;

namespace Neuron::Graphics
{
  namespace
  {
    // Mirrors BlurCb in blurPS.hlsl.
    struct BlurConstants { float dir[4]; };
    // Mirrors CompositeCb in compositePS.hlsl.
    struct CompositeConstants { float params[4]; };

    // Create one full-size colour texture with both a render-target and a shader-resource
    // view (the post chain writes it in one pass, samples it in the next).
    bool makeTarget(ID3D11Device* _dev, UINT _w, UINT _h, DXGI_FORMAT _fmt, com_ptr<ID3D11Texture2D>& _tex,
                    com_ptr<ID3D11RenderTargetView>& _rtv, com_ptr<ID3D11ShaderResourceView>& _srv)
    {
      _tex = nullptr;
      _rtv = nullptr;
      _srv = nullptr;

      D3D11_TEXTURE2D_DESC td{};
      td.Width = _w;
      td.Height = _h;
      td.MipLevels = 1;
      td.ArraySize = 1;
      td.Format = _fmt;
      td.SampleDesc.Count = 1;
      td.Usage = D3D11_USAGE_DEFAULT;
      td.BindFlags = D3D11_BIND_RENDER_TARGET | D3D11_BIND_SHADER_RESOURCE;
      if (FAILED(_dev->CreateTexture2D(&td, nullptr, _tex.put())))
        return false;
      if (FAILED(_dev->CreateRenderTargetView(_tex.get(), nullptr, _rtv.put())))
        return false;
      if (FAILED(_dev->CreateShaderResourceView(_tex.get(), nullptr, _srv.put())))
        return false;
      return true;
    }
  } // namespace

  void SceneGlow::Startup() { Shutdown(); }

  void SceneGlow::Shutdown()
  {
    s_sceneTex = nullptr;
    s_sceneRtv = nullptr;
    s_sceneSrv = nullptr;
    s_blurTexA = nullptr;
    s_blurRtvA = nullptr;
    s_blurSrvA = nullptr;
    s_blurTexB = nullptr;
    s_blurRtvB = nullptr;
    s_blurSrvB = nullptr;
    s_postVs = nullptr;
    s_blurPs = nullptr;
    s_compositePs = nullptr;
    s_blurCb = nullptr;
    s_compositeCb = nullptr;
    s_sampler = nullptr;
    s_raster = nullptr;
    s_w = 0;
    s_h = 0;
    s_progReady = false;
    // s_enabled / s_intensity are settings; keep them across device resets.
  }

  bool SceneGlow::EnsureResources(UINT _w, UINT _h)
  {
    ID3D11Device* device = Core::GetD3DDevice();
    if (!device || _w == 0 || _h == 0)
      return false;

    // One-time programs + sampler + state.
    if (!s_progReady)
    {
      check_hresult(device->CreateVertexShader(g_postVS, sizeof(g_postVS), nullptr, s_postVs.put()));
      check_hresult(device->CreatePixelShader(g_blurPS, sizeof(g_blurPS), nullptr, s_blurPs.put()));
      check_hresult(device->CreatePixelShader(g_compositePS, sizeof(g_compositePS), nullptr, s_compositePs.put()));

      D3D11_BUFFER_DESC cbd{};
      cbd.ByteWidth = sizeof(BlurConstants);
      cbd.Usage = D3D11_USAGE_DYNAMIC;
      cbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
      cbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
      check_hresult(device->CreateBuffer(&cbd, nullptr, s_blurCb.put()));
      cbd.ByteWidth = sizeof(CompositeConstants);
      check_hresult(device->CreateBuffer(&cbd, nullptr, s_compositeCb.put()));

      // Linear clamp: the blur samples between texels; clamp keeps the glow from wrapping.
      D3D11_SAMPLER_DESC sd{};
      sd.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
      sd.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;
      sd.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
      sd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
      sd.ComparisonFunc = D3D11_COMPARISON_NEVER;
      sd.MaxLOD = D3D11_FLOAT32_MAX;
      check_hresult(device->CreateSamplerState(&sd, s_sampler.put()));

      // Cull none: the SV_VertexID full-screen triangle needs no winding assumption.
      D3D11_RASTERIZER_DESC rd{};
      rd.FillMode = D3D11_FILL_SOLID;
      rd.CullMode = D3D11_CULL_NONE;
      rd.DepthClipEnable = TRUE;
      check_hresult(device->CreateRasterizerState(&rd, s_raster.put()));

      s_progReady = true;
    }

    // (Re)build the size-dependent targets when the back buffer size changes.
    if (s_w != _w || s_h != _h || !s_sceneRtv)
    {
      const DXGI_FORMAT fmt = Core::GetBackBufferFormat();
      if (!makeTarget(device, _w, _h, fmt, s_sceneTex, s_sceneRtv, s_sceneSrv) ||
          !makeTarget(device, _w, _h, fmt, s_blurTexA, s_blurRtvA, s_blurSrvA) ||
          !makeTarget(device, _w, _h, fmt, s_blurTexB, s_blurRtvB, s_blurSrvB))
      {
        s_w = 0;
        s_h = 0;
        return false;
      }
      s_w = _w;
      s_h = _h;
    }
    return true;
  }

  ID3D11RenderTargetView* SceneGlow::Begin()
  {
    if (!s_enabled)
      return nullptr;

    ID3D11Texture2D* back = Core::GetRenderTarget();
    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!back || !ctx)
      return nullptr;

    D3D11_TEXTURE2D_DESC bd{};
    back->GetDesc(&bd);
    if (!EnsureResources(bd.Width, bd.Height))
      return nullptr;

    // Clear the scene target to the same space-black the engine clears the back buffer to
    // (the scene pass clears depth only and composites over a pre-cleared colour target).
    const float black[4] = {0.0f, 0.0f, 0.0f, 1.0f};
    ctx->ClearRenderTargetView(s_sceneRtv.get(), black);
    return s_sceneRtv.get();
  }

  void SceneGlow::drawFullscreen()
  {
    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    // No vertex/index buffer: postVS builds the triangle from SV_VertexID.
    ctx->IASetInputLayout(nullptr);
    ID3D11Buffer* noVb = nullptr;
    const UINT zero = 0;
    ctx->IASetVertexBuffers(0, 1, &noVb, &zero, &zero);
    ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    ctx->Draw(3, 0);
  }

  void SceneGlow::Composite(ID3D11RenderTargetView* _backBuffer)
  {
    ID3D11DeviceContext* ctx = Core::GetD3DDeviceContext();
    if (!ctx || !_backBuffer || !s_sceneRtv)
      return;

    D3D11_VIEWPORT vp{};
    vp.Width = static_cast<float>(s_w);
    vp.Height = static_cast<float>(s_h);
    vp.MinDepth = 0.0f;
    vp.MaxDepth = 1.0f;
    ctx->RSSetViewports(1, &vp);
    ctx->RSSetState(s_raster.get());
    ctx->OMSetDepthStencilState(nullptr, 0);         // depth off
    ctx->OMSetBlendState(nullptr, nullptr, 0xFFFFFFFF); // opaque replace
    ctx->VSSetShader(s_postVs.get(), nullptr, 0);
    ID3D11SamplerState* smp = s_sampler.get();
    ctx->PSSetSamplers(0, 1, &smp);

    // --- Pass 1: horizontal blur of the scene into blur target A -----------------------
    {
      BlurConstants bc{};
      bc.dir[0] = 1.0f / static_cast<float>(s_w);
      bc.dir[1] = 0.0f;
      D3D11_MAPPED_SUBRESOURCE m;
      if (SUCCEEDED(ctx->Map(s_blurCb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &m)))
      {
        std::memcpy(m.pData, &bc, sizeof(bc));
        ctx->Unmap(s_blurCb.get(), 0);
      }
      ID3D11RenderTargetView* rtv = s_blurRtvA.get();
      ctx->OMSetRenderTargets(1, &rtv, nullptr);
      ID3D11ShaderResourceView* src = s_sceneSrv.get();
      ctx->PSSetShader(s_blurPs.get(), nullptr, 0);
      ctx->PSSetShaderResources(0, 1, &src);
      ID3D11Buffer* cb = s_blurCb.get();
      ctx->PSSetConstantBuffers(0, 1, &cb);
      drawFullscreen();
      ID3D11ShaderResourceView* nullSrv = nullptr;
      ctx->PSSetShaderResources(0, 1, &nullSrv); // unbind A's source before A becomes a source
    }

    // --- Pass 2: vertical blur of A into blur target B ---------------------------------
    {
      BlurConstants bc{};
      bc.dir[0] = 0.0f;
      bc.dir[1] = 1.0f / static_cast<float>(s_h);
      D3D11_MAPPED_SUBRESOURCE m;
      if (SUCCEEDED(ctx->Map(s_blurCb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &m)))
      {
        std::memcpy(m.pData, &bc, sizeof(bc));
        ctx->Unmap(s_blurCb.get(), 0);
      }
      ID3D11RenderTargetView* rtv = s_blurRtvB.get();
      ctx->OMSetRenderTargets(1, &rtv, nullptr);
      ID3D11ShaderResourceView* src = s_blurSrvA.get();
      ctx->PSSetShaderResources(0, 1, &src);
      drawFullscreen();
      ID3D11ShaderResourceView* nullSrv = nullptr;
      ctx->PSSetShaderResources(0, 1, &nullSrv);
    }

    // --- Composite: sharp scene + blurred glow onto the back buffer --------------------
    {
      CompositeConstants cc{};
      cc.params[0] = s_intensity;
      D3D11_MAPPED_SUBRESOURCE m;
      if (SUCCEEDED(ctx->Map(s_compositeCb.get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &m)))
      {
        std::memcpy(m.pData, &cc, sizeof(cc));
        ctx->Unmap(s_compositeCb.get(), 0);
      }
      ctx->OMSetRenderTargets(1, &_backBuffer, nullptr);
      ctx->PSSetShader(s_compositePs.get(), nullptr, 0);
      ID3D11ShaderResourceView* srvs[2] = {s_sceneSrv.get(), s_blurSrvB.get()};
      ctx->PSSetShaderResources(0, 2, srvs);
      ID3D11Buffer* cb = s_compositeCb.get();
      ctx->PSSetConstantBuffers(0, 1, &cb);
      drawFullscreen();
      ID3D11ShaderResourceView* nullSrvs[2] = {nullptr, nullptr};
      ctx->PSSetShaderResources(0, 2, nullSrvs); // release the scene/glow targets for next frame
    }
  }
}
